### ISSUE TITLE
Make @SystemProperty a @Repeatable annotation

### ISSUE THREAD

**Issue by sbrannen** [glytching/junit-extensions#1]
Since JUnit Jupiter requires Java 8, why don't you just simply configuration by making `@SystemProperty` a `@Repeatable` annotation?

**Comment by glytching** [comment]
Thanks for pointing that out.

I've merged this change and bumped the version to `2.0.0-SNAPSHOT`.

I'll cut a new release and push to Maven Central some time in the next few days.

**Comment by glytching** [comment]
Done, [v2.0.0](https://github.com/glytching/junit-extensions/releases/tag/v2.0.0) has been released.

**Comment by sbrannen** [comment]
> Thanks for pointing that out.

You're welcome!

> Done, v2.0.0 has been released.

Wow... that was fast!

But perhaps a bit too fast: see #3. 😉

**Comment by glytching** [comment]
That's ok :)

I'll have a look at [#3](https://github.com/glytching/junit-extensions/issues/3) and if a fix is required I'll apply it and leave 2.1.0-SNAPSHOT open for a week or two.

BTW, thanks for raising these issues, much appreciated.
