### ISSUE TITLE
ExpectedExceptionExtension should fail test if no exception is thrown

### ISSUE THREAD

**Issue by sbrannen** [glytching/junit-extensions#3]
As pointed out by @marcphilipp, `ExpectedExceptionExtension` currently allows a test to pass if no exception is thrown; whereas, the use of `ExpectedExceptionExtension` is a clear indication that the user expects an exception to be thrown. Thus, the absence of an exception must fail the test.

**Comment by sbrannen** [comment]
Oh wait, I do see that it ends with `throw throwable;`.

So if you have tests to confirm the "unexpected" behavior, then just ignore this issue.

**Comment by sbrannen** [comment]
Except that.... `if (throwable.getClass() == annotation.type())` should really check for a subtype instead of an exact match. 😉

**Comment by glytching** [comment]
Will have a look, thanks.

**Comment by marcphilipp** [comment]
Actually, what I meant was, that the extension should throw an exception to fail the test in the case when the test method does not throw any exception at all, i.e. it should implement `AfterTestExecutionCallback` and check whether `ExtensionContext.getExecutionException()` matches the expectations.

**Comment by glytching** [comment]
The paths where the caller's expectation is not met (and therefore the extension _must_ throw) is covered, I think, in `ExpectedExceptionExtensionMetaTest`.

I'll have a look at the comment from @marcphilipp, on the face of it that does look like a gap.

Thanks

**Comment by marcphilipp** [comment]
The following test should fail IMHO. Instead, it passes.

```java
@Test
@ExpectedException(type = Throwable.class)
public void failsTestForMissingException() {}
```

**Comment by marcphilipp** [comment]
> I'm open to suggestions on what `XXXException` should be.

I would use `Assertions.fail()` because it's like an assertion in test code.

**Comment by glytching** [comment]
Ok, PR raised, thanks for the suggestion.

**Comment by sbrannen** [comment]
> Actually, what I meant was that the extension should throw an exception to fail the test in the case when the test method does not throw any exception at all

Oops... Sorry for misrepresenting you.

I'll change the title and description of this issue accordingly.

**Comment by sbrannen** [comment]
> `if (throwable.getClass() == annotation.type())` should really check for a subtype instead of an exact match.

@glytching, would you like for me to raise a separate issue for this bug?

**Comment by glytching** [comment]
@sbrannen yes, please.

I'm not 100% convinced about the use case for that so it would be useful to discuss it on a separate issue.

Thanks

**Comment by sbrannen** [comment]
Done: see #5

**Comment by glytching** [comment]
PR merged.

Green build: https://travis-ci.org/glytching/junit-extensions/builds/338930351
