### ISSUE TITLE
null-Value (usage problem?)

### ISSUE THREAD

**Issue by toweih** [glytching/junit-extensions#7]
## Expected Behavior

I want a String to be populated with a random value

## Actual Behavior

Member anyString stays <code>null</code>

## Steps to Reproduce the Problem

```
import io.github.glytching.junit.extension.random.Random;
import io.github.glytching.junit.extension.random.RandomBeansExtension;

import java.util.List;

import org.junit.Test;
import org.junit.Assert;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@ComponentScan
@SpringBootTest
@ExtendWith(RandomBeansExtension.class)
public class MyServiceTest {

    @Random private String anyString;
    
    @Random(type = String.class)
    private List<String> listOfStrings;
    
	@Test
	@ExtendWith(RandomBeansExtension.class)
	public void notNull() {
               	Assert.assertNotNull(anyString);
		Assert.assertNotNull(listOfStrings);
	}
}
```

**Comment by glytching** [comment]
Apologies for the delayed response, will have a look at this and reply tomorrow.

Rgds

**Comment by toweih** [comment]
[solved]
Oh, I didn't know that. After upgrading to JUnit 5 it works like a charm.

pom.xml:
'''
		
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.1.0</version>
			<scope>test</scope>
		</dependency>		

		
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-launcher</artifactId>
			<version>1.1.0</version>
			<scope>test</scope>
		</dependency>		
'''
Thank you!

**Comment by glytching** [comment]
No problem, glad to help.

Rgds
